[deployment]
deploymentStrategy = "nixpacks"
src = "frontend"
buildCommand = "cd frontend && npm install && npm run build"
startCommand = "cd frontend && npm run start"

[project]
name = "AI-MWD-Copilot"
id = "c9058b41-703d-46e0-8b63-e9ecaa378a0d"
service = "insightful-commitment"